language: node_js
node_js:
    - 10
env:
    - GENERATE_SOURCEMAP=false
cache:
    directories:
        - node_modules
        - build

before_script:
    - cp .npmrc.dist .npmrc && yarn install

script:
    - yarn build

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
        branch: master
