language: node_js
addons:
  chrome: stable
node_js:
    - 14
env:
    - GENERATE_SOURCEMAP=false
cache:
    yarn: true
    directories:
        - build

before_install:
  # Repo for Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH=$HOME/.yarn/bin:$PATH
  - cp .npmrc.dist .npmrc

install:
    - yarn install
    - yarn cypress install
    - yarn cypress verify

script:
    - make build
    - make e2e

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
        branch: master
