language: node_js
node_js:
    - 14
env:
    - GENERATE_SOURCEMAP=false
cache:
    directories:
        - node_modules
        - build

before_install:
    - cp .npmrc.dist .npmrc

install:
    - yarn install

script:
    - yarn build
    - yarn 

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    keep_history: true
    on:
        branch: master
