export default {
    tours: [
        {
            id: 1,
            image: 'images/tours/ra-markdown.jpg',
            title: 'ra-markdown',
            tour: 'ra-markdown',
            comment: `Read Markdown data, and edit it using a WYSIWYG editor in your admin`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
        {
            id: 2,
            image: 'images/tours/ra-preferences.jpg',
            title: 'ra-preferences',
            tour: 'ra-preferences',
            comment: `Persist user preferences (language, ui, filters, displayed columns, etc) in local storage`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
        {
            id: 3,
            image: 'images/tours/ra-tree.jpg',
            title: 'ra-tree',
            tour: 'ra-tree',
            comment: `Edit and visualize tree structures. Reorganize by drag and drop. Adapts to any data structure on the backend (parent_id, children, nested sets, etc)..`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
        {
            id: 4,
            image: 'images/tours/ra-realtime.jpg',
            title: 'ra-realtime',
            tour: 'ra-realtime',
            comment: `Enable realtime on menu, list, show and edit views - or anywhere you want.`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
        {
            id: 5,
            image: 'images/tours/ra-editable-datagrid.jpg',
            title: 'ra-editable-datagrid',
            tour: 'ra-editable-datagrid',
            comment: `Quickly edit your data without leaving your datagrid.`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
        {
            id: 6,
            image: 'images/tours/ra-navigation-breadcrumb.jpg',
            title: 'ra-navigation: Breadcrumb',
            tour: 'ra-navigation-breadcrumb',
            comment: `Keep a track of your location in the site and navigate easily.`,
            href: 'http://marmelab.com/react-admin',
            playedOn: null,
        },
    ],
};
