export default {
  commands: [
    {
      id: 416,
      reference: "UOSXL6",
      date: "2020-07-03T05:05:49.512Z",
      customer_id: 662,
      basket: [{ product_id: 26, quantity: 1 }],
      total_ex_taxes: 18.49,
      delivery_fees: 6.2,
      tax_rate: 0.17,
      taxes: 4.2,
      total: 28.89,
      status: "ordered",
      returned: false,
      batch: 1,
    },
    {
      id: 593,
      reference: "IRLI2J",
      date: "2020-06-26T00:11:32.254Z",
      customer_id: 169,
      basket: [{ product_id: 51, quantity: 1 }],
      total_ex_taxes: 27,
      delivery_fees: 4.91,
      tax_rate: 0.2,
      taxes: 6.38,
      total: 38.29,
      status: "ordered",
      returned: false,
      batch: 0,
    },
    {
      id: 35,
      reference: "DY218C",
      date: "2020-06-22T15:36:00.831Z",
      customer_id: 884,
      basket: [
        { product_id: 123, quantity: 1 },
        { product_id: 127, quantity: 1 },
      ],
      total_ex_taxes: 56.95,
      delivery_fees: 7.53,
      tax_rate: 0.17,
      taxes: 10.96,
      total: 75.44,
      status: "ordered",
      returned: false,
      batch: 0,
    },
    {
      id: 85,
      reference: "4UCGSS",
      date: "2020-07-13T02:45:35.791Z",
      customer_id: 244,
      basket: [{ product_id: 87, quantity: 4 }],
      total_ex_taxes: 108,
      delivery_fees: 6.32,
      tax_rate: 0.12,
      taxes: 13.72,
      total: 128.04,
      status: "ordered",
      returned: false,
      batch: 2,
    },
    {
      id: 94,
      reference: "9ONX5O",
      date: "2020-07-01T22:20:54.584Z",
      customer_id: 197,
      basket: [
        { product_id: 124, quantity: 3 },
        { product_id: 94, quantity: 3 },
        { product_id: 117, quantity: 2 },
        { product_id: 91, quantity: 1 },
        { product_id: 4, quantity: 3 },
      ],
      total_ex_taxes: 435.47,
      delivery_fees: 3.78,
      tax_rate: 0.2,
      taxes: 87.85,
      total: 527.1,
      status: "ordered",
      returned: false,
      batch: 1,
    },
    {
      id: 330,
      reference: "WH8JL9",
      date: "2020-07-01T21:13:42.263Z",
      customer_id: 572,
      basket: [{ product_id: 49, quantity: 4 }],
      total_ex_taxes: 110.2,
      delivery_fees: 6.27,
      tax_rate: 0.17,
      taxes: 19.8,
      total: 136.27,
      status: "ordered",
      returned: false,
      batch: 1,
    },
    {
      id: 451,
      reference: "D3MVC2",
      date: "2020-06-29T14:33:38.660Z",
      customer_id: 792,
      basket: [
        { product_id: 116, quantity: 2 },
        { product_id: 110, quantity: 2 },
      ],
      total_ex_taxes: 179.78,
      delivery_fees: 5.73,
      tax_rate: 0.17,
      taxes: 31.54,
      total: 217.05,
      status: "ordered",
      returned: false,
      batch: 1,
    },

    {
      id: 401,
      reference: "1STBTX",
      date: "2020-07-17T06:54:06.382Z",
      customer_id: 604,
      basket: [{ product_id: 91, quantity: 2 }],
      total_ex_taxes: 48.1,
      delivery_fees: 6.2,
      tax_rate: 0.12,
      taxes: 6.52,
      total: 60.82,
      status: "ordered",
      returned: false,
      batch: 2,
    },
    {
      id: 329,
      reference: "ZRWGMI",
      date: "2020-07-17T03:32:31.117Z",
      customer_id: 337,
      basket: [{ product_id: 65, quantity: 1 }],
      total_ex_taxes: 19.48,
      delivery_fees: 3.51,
      tax_rate: 0.2,
      taxes: 4.6,
      total: 27.59,
      status: "ordered",
      returned: false,
      batch: 2,
    },
    {
      id: 293,
      reference: "7ZEFKO",
      date: "2020-07-11T05:15:08.146Z",
      customer_id: 656,
      basket: [{ product_id: 115, quantity: 1 }],
      total_ex_taxes: 21.97,
      delivery_fees: 4.38,
      tax_rate: 0.12,
      taxes: 3.16,
      total: 29.51,
      status: "ordered",
      returned: false,
      batch: 2,
    },
    {
      id: 403,
      reference: "12GFIW",
      date: "2020-07-05T22:16:34.543Z",
      customer_id: 121,
      basket: [
        { product_id: 8, quantity: 4 },
        { product_id: 105, quantity: 1 },
      ],
      total_ex_taxes: 294.8,
      delivery_fees: 7.61,
      tax_rate: 0.17,
      taxes: 51.41,
      total: 353.82,
      status: "ordered",
      returned: false,
      batch: 1,
    },
    {
      id: 591,
      reference: "5HXSKK",
      date: "2020-06-27T23:36:58.939Z",
      customer_id: 342,
      basket: [{ product_id: 87, quantity: 1 }],
      total_ex_taxes: 34.14,
      delivery_fees: 6.38,
      tax_rate: 0.12,
      taxes: 4.86,
      total: 45.38,
      status: "ordered",
      returned: false,
      batch: 0,
    },
    {
      id: 133,
      reference: "05TVTI",
      date: "2020-06-24T13:03:34.361Z",
      customer_id: 119,
      basket: [{ product_id: 64, quantity: 1 }],
      total_ex_taxes: 30.22,
      delivery_fees: 7.63,
      tax_rate: 0.17,
      taxes: 6.43,
      total: 44.28,
      status: "ordered",
      returned: false,
      batch: 0,
    },
    {
      id: 411,
      reference: "CPKIKP",
      date: "2020-07-15T10:46:27.993Z",
      customer_id: 11,
      basket: [
        { product_id: 34, quantity: 2 },
        { product_id: 67, quantity: 1 },
        { product_id: 55, quantity: 4 },
      ],
      total_ex_taxes: 188.04,
      delivery_fees: 3.75,
      tax_rate: 0.17,
      taxes: 32.6,
      total: 224.39,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 202,
      reference: "CV1D5Z",
      date: "2020-07-13T04:14:17.489Z",
      customer_id: 641,
      basket: [
        { product_id: 45, quantity: 1 },
        { product_id: 80, quantity: 3 },
        { product_id: 30, quantity: 1 },
      ],
      total_ex_taxes: 196.3,
      delivery_fees: 7,
      tax_rate: 0.2,
      taxes: 40.66,
      total: 243.96,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 461,
      reference: "FE4H7T",
      date: "2020-07-10T02:30:33.592Z",
      customer_id: 316,
      basket: [
        { product_id: 109, quantity: 3 },
        { product_id: 87, quantity: 1 },
      ],
      total_ex_taxes: 55.17,
      delivery_fees: 3.11,
      tax_rate: 0.12,
      taxes: 6.99,
      total: 65.27,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 365,
      reference: "PEUJ6B",
      date: "2020-07-08T01:28:28.777Z",
      customer_id: 412,
      basket: [
        { product_id: 39, quantity: 1 },
        { product_id: 127, quantity: 1 },
      ],
      total_ex_taxes: 55.03,
      delivery_fees: 6.91,
      tax_rate: 0.17,
      taxes: 10.53,
      total: 72.47,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 116,
      reference: "HEC9B6",
      date: "2020-06-26T12:24:51.869Z",
      customer_id: 661,
      basket: [{ product_id: 109, quantity: 1 }],
      total_ex_taxes: 7.01,
      delivery_fees: 6.1,
      tax_rate: 0.17,
      taxes: 2.23,
      total: 15.34,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 16,
      reference: "6UW63X",
      date: "2020-06-16T11:16:05.334Z",
      customer_id: 602,
      basket: [{ product_id: 8, quantity: 2 }],
      total_ex_taxes: 135.62,
      delivery_fees: 7.86,
      tax_rate: 0.12,
      taxes: 17.22,
      total: 160.7,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 465,
      reference: "0STZOE",
      date: "2020-06-13T02:50:14.320Z",
      customer_id: 562,
      basket: [{ product_id: 124, quantity: 3 }],
      total_ex_taxes: 109.97999999999999,
      delivery_fees: 6.1,
      tax_rate: 0.17,
      taxes: 19.73,
      total: 135.81,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 322,
      reference: "HGWVT4",
      date: "2020-06-12T21:59:23.748Z",
      customer_id: 127,
      basket: [
        { product_id: 65, quantity: 1 },
        { product_id: 107, quantity: 3 },
        { product_id: 123, quantity: 2 },
        { product_id: 50, quantity: 3 },
        { product_id: 13, quantity: 3 },
        { product_id: 117, quantity: 1 },
        { product_id: 85, quantity: 3 },
        { product_id: 69, quantity: 2 },
        { product_id: 55, quantity: 1 },
      ],
      total_ex_taxes: 680.53,
      delivery_fees: 6.08,
      tax_rate: 0.17,
      taxes: 116.72,
      total: 803.33,
      status: "delivered",
      returned: true,
    },
    {
      id: 483,
      reference: "X84DYC",
      date: "2020-06-08T09:55:49.975Z",
      customer_id: 320,
      basket: [
        { product_id: 12, quantity: 1 },
        { product_id: 101, quantity: 1 },
        { product_id: 108, quantity: 2 },
      ],
      total_ex_taxes: 152.61,
      delivery_fees: 6.28,
      tax_rate: 0.12,
      taxes: 19.07,
      total: 177.96,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 31,
      reference: "N79HP1",
      date: "2020-06-07T10:20:37.584Z",
      customer_id: 234,
      basket: [{ product_id: 23, quantity: 1 }],
      total_ex_taxes: 38.01,
      delivery_fees: 3.67,
      tax_rate: 0.17,
      taxes: 7.09,
      total: 48.77,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 327,
      reference: "L4PT26",
      date: "2020-06-05T14:10:48.577Z",
      customer_id: 483,
      basket: [{ product_id: 69, quantity: 3 }],
      total_ex_taxes: 63.72,
      delivery_fees: 5.32,
      tax_rate: 0.2,
      taxes: 13.81,
      total: 82.85,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 3,
      reference: "8QJG92",
      date: "2020-06-05T02:43:19.002Z",
      customer_id: 632,
      basket: [{ product_id: 25, quantity: 2 }],
      total_ex_taxes: 25.7,
      delivery_fees: 3.57,
      tax_rate: 0.12,
      taxes: 3.51,
      total: 32.78,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 19,
      reference: "LTJW8S",
      date: "2020-06-04T17:47:24.952Z",
      customer_id: 485,
      basket: [{ product_id: 96, quantity: 1 }],
      total_ex_taxes: 51.71,
      delivery_fees: 5.77,
      tax_rate: 0.17,
      taxes: 9.77,
      total: 67.25,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 389,
      reference: "BY4JEB",
      date: "2020-06-04T14:48:44.623Z",
      customer_id: 697,
      basket: [{ product_id: 29, quantity: 5 }],
      total_ex_taxes: 277.04999999999995,
      delivery_fees: 3.17,
      tax_rate: 0.2,
      taxes: 56.04,
      total: 336.26,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 504,
      reference: "NEXJ58",
      date: "2020-06-04T01:15:29.735Z",
      customer_id: 652,
      basket: [
        { product_id: 87, quantity: 1 },
        { product_id: 54, quantity: 1 },
      ],
      total_ex_taxes: 81.48,
      delivery_fees: 7.25,
      tax_rate: 0.2,
      taxes: 17.75,
      total: 106.48,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 373,
      reference: "01SPMI",
      date: "2020-05-30T13:16:11.908Z",
      customer_id: 656,
      basket: [
        { product_id: 88, quantity: 3 },
        { product_id: 44, quantity: 1 },
        { product_id: 129, quantity: 1 },
        { product_id: 36, quantity: 2 },
        { product_id: 109, quantity: 1 },
        { product_id: 108, quantity: 5 },
      ],
      total_ex_taxes: 380.15,
      delivery_fees: 3.24,
      tax_rate: 0.17,
      taxes: 65.18,
      total: 448.57,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 588,
      reference: "04WJP4",
      date: "2020-05-27T13:07:26.459Z",
      customer_id: 247,
      basket: [{ product_id: 38, quantity: 1 }],
      total_ex_taxes: 30.7,
      delivery_fees: 5.98,
      tax_rate: 0.12,
      taxes: 4.4,
      total: 41.08,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 571,
      reference: "CJOFRC",
      date: "2020-05-23T19:56:53.453Z",
      customer_id: 891,
      basket: [
        { product_id: 0, quantity: 2 },
        { product_id: 123, quantity: 3 },
      ],
      total_ex_taxes: 170.4,
      delivery_fees: 7.29,
      tax_rate: 0.2,
      taxes: 35.54,
      total: 213.23,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 590,
      reference: "2RFCT4",
      date: "2020-05-22T13:14:09.836Z",
      customer_id: 43,
      basket: [{ product_id: 39, quantity: 5 }],
      total_ex_taxes: 129.35,
      delivery_fees: 4.7,
      tax_rate: 0.2,
      taxes: 26.81,
      total: 160.86,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 75,
      reference: "GW2HK0",
      date: "2020-05-22T07:03:27.440Z",
      customer_id: 491,
      basket: [
        { product_id: 50, quantity: 1 },
        { product_id: 69, quantity: 1 },
      ],
      total_ex_taxes: 94.53999999999999,
      delivery_fees: 4.07,
      tax_rate: 0.17,
      taxes: 16.76,
      total: 115.37,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 496,
      reference: "P7XLCA",
      date: "2020-05-21T03:49:51.637Z",
      customer_id: 210,
      basket: [
        { product_id: 59, quantity: 2 },
        { product_id: 46, quantity: 5 },
      ],
      total_ex_taxes: 157.08999999999997,
      delivery_fees: 5.73,
      tax_rate: 0.2,
      taxes: 32.56,
      total: 195.38,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 197,
      reference: "JO52RO",
      date: "2020-05-15T02:13:40.525Z",
      customer_id: 8,
      basket: [
        { product_id: 85, quantity: 1 },
        { product_id: 88, quantity: 4 },
      ],
      total_ex_taxes: 86.25,
      delivery_fees: 4.79,
      tax_rate: 0.17,
      taxes: 15.48,
      total: 106.52,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 64,
      reference: "65W8TD",
      date: "2020-05-10T03:10:06.968Z",
      customer_id: 435,
      basket: [{ product_id: 50, quantity: 1 }],
      total_ex_taxes: 73.3,
      delivery_fees: 6.66,
      tax_rate: 0.12,
      taxes: 9.6,
      total: 89.56,
      status: "delivered",
      returned: true,
    },
    {
      id: 318,
      reference: "ZIDQ9Y",
      date: "2020-05-04T04:22:00.257Z",
      customer_id: 656,
      basket: [{ product_id: 67, quantity: 2 }],
      total_ex_taxes: 93.16,
      delivery_fees: 6.63,
      tax_rate: 0.12,
      taxes: 11.97,
      total: 111.76,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 580,
      reference: "ZHXYDF",
      date: "2020-04-30T23:45:07.580Z",
      customer_id: 76,
      basket: [
        { product_id: 43, quantity: 3 },
        { product_id: 101, quantity: 2 },
        { product_id: 113, quantity: 4 },
      ],
      total_ex_taxes: 329.03,
      delivery_fees: 3.76,
      tax_rate: 0.12,
      taxes: 39.93,
      total: 372.72,
      status: "delivered",
      returned: false,
      batch: 0,
    },
    {
      id: 525,
      reference: "OWROKF",
      date: "2020-07-04T03:49:49.697Z",
      customer_id: 0,
      basket: [{ product_id: 68, quantity: 1 }],
      total_ex_taxes: 37.79,
      delivery_fees: 7.8,
      tax_rate: 0.17,
      taxes: 7.75,
      total: 53.34,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 181,
      reference: "Z5ZLFN",
      date: "2020-06-06T06:51:45.426Z",
      customer_id: 119,
      basket: [
        { product_id: 57, quantity: 3 },
        { product_id: 63, quantity: 4 },
      ],
      total_ex_taxes: 490.32,
      delivery_fees: 6.89,
      tax_rate: 0.12,
      taxes: 59.67,
      total: 556.88,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 481,
      reference: "YYVI8N",
      date: "2020-05-18T16:30:54.934Z",
      customer_id: 544,
      basket: [
        { product_id: 58, quantity: 1 },
        { product_id: 19, quantity: 2 },
      ],
      total_ex_taxes: 68.67,
      delivery_fees: 5.34,
      tax_rate: 0.12,
      taxes: 8.88,
      total: 82.89,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 61,
      reference: "W5BWES",
      date: "2020-05-18T13:20:53.237Z",
      customer_id: 41,
      basket: [
        { product_id: 125, quantity: 3 },
        { product_id: 53, quantity: 2 },
      ],
      total_ex_taxes: 247.13,
      delivery_fees: 4.97,
      tax_rate: 0.17,
      taxes: 42.86,
      total: 294.96,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 178,
      reference: "XY6QM6",
      date: "2020-05-12T19:46:17.915Z",
      customer_id: 354,
      basket: [{ product_id: 36, quantity: 4 }],
      total_ex_taxes: 137.92,
      delivery_fees: 6.4,
      tax_rate: 0.12,
      taxes: 17.32,
      total: 161.64,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 546,
      reference: "BII2V1",
      date: "2020-05-11T13:18:57.179Z",
      customer_id: 652,
      basket: [{ product_id: 109, quantity: 3 }],
      total_ex_taxes: 21.03,
      delivery_fees: 7.49,
      tax_rate: 0.17,
      taxes: 4.85,
      total: 33.37,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 41,
      reference: "B34IQG",
      date: "2020-05-03T15:13:33.118Z",
      customer_id: 628,
      basket: [{ product_id: 20, quantity: 1 }],
      total_ex_taxes: 37.86,
      delivery_fees: 5.22,
      tax_rate: 0.12,
      taxes: 5.17,
      total: 48.25,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 566,
      reference: "R2BWLT",
      date: "2020-04-28T07:01:21.398Z",
      customer_id: 533,
      basket: [{ product_id: 81, quantity: 1 }],
      total_ex_taxes: 46.25,
      delivery_fees: 7.15,
      tax_rate: 0.17,
      taxes: 9.08,
      total: 62.48,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 457,
      reference: "HU7Y4I",
      date: "2020-03-28T04:53:58.987Z",
      customer_id: 446,
      basket: [
        { product_id: 108, quantity: 1 },
        { product_id: 103, quantity: 1 },
        { product_id: 79, quantity: 1 },
      ],
      total_ex_taxes: 136.81,
      delivery_fees: 6.88,
      tax_rate: 0.12,
      taxes: 17.24,
      total: 160.93,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 87,
      reference: "9LVNAL",
      date: "2020-03-25T07:17:17.932Z",
      customer_id: 354,
      basket: [
        { product_id: 11, quantity: 4 },
        { product_id: 122, quantity: 5 },
      ],
      total_ex_taxes: 169.04999999999998,
      delivery_fees: 4.9,
      tax_rate: 0.2,
      taxes: 34.79,
      total: 208.74,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 136,
      reference: "Z4G9JX",
      date: "2020-03-05T23:18:19.780Z",
      customer_id: 255,
      basket: [{ product_id: 26, quantity: 4 }],
      total_ex_taxes: 125.56,
      delivery_fees: 3.72,
      tax_rate: 0.2,
      taxes: 25.86,
      total: 155.14,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 567,
      reference: "SR6QP5",
      date: "2020-03-02T20:09:07.479Z",
      customer_id: 353,
      basket: [
        { product_id: 70, quantity: 1 },
        { product_id: 67, quantity: 2 },
      ],
      total_ex_taxes: 117.83,
      delivery_fees: 7.69,
      tax_rate: 0.2,
      taxes: 25.1,
      total: 150.62,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 548,
      reference: "GBYAOY",
      date: "2020-02-29T00:26:19.163Z",
      customer_id: 747,
      basket: [
        { product_id: 31, quantity: 1 },
        { product_id: 53, quantity: 2 },
      ],
      total_ex_taxes: 153.63,
      delivery_fees: 6.38,
      tax_rate: 0.17,
      taxes: 27.2,
      total: 187.21,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 356,
      reference: "RBV1FN",
      date: "2020-02-19T22:39:39.119Z",
      customer_id: 604,
      basket: [{ product_id: 85, quantity: 3 }],
      total_ex_taxes: 66.15,
      delivery_fees: 7.83,
      tax_rate: 0.17,
      taxes: 12.58,
      total: 86.56,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 501,
      reference: "3T6PI8",
      date: "2020-02-10T20:16:43.753Z",
      customer_id: 262,
      basket: [
        { product_id: 49, quantity: 2 },
        { product_id: 123, quantity: 4 },
      ],
      total_ex_taxes: 177.06,
      delivery_fees: 6.89,
      tax_rate: 0.2,
      taxes: 36.79,
      total: 220.74,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 96,
      reference: "EH97YV",
      date: "2020-02-08T01:58:56.343Z",
      customer_id: 650,
      basket: [
        { product_id: 11, quantity: 5 },
        { product_id: 12, quantity: 1 },
      ],
      total_ex_taxes: 124.2,
      delivery_fees: 7.97,
      tax_rate: 0.17,
      taxes: 22.47,
      total: 154.64,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 581,
      reference: "D4K6H4",
      date: "2020-01-16T04:32:12.929Z",
      customer_id: 270,
      basket: [{ product_id: 74, quantity: 1 }],
      total_ex_taxes: 37.74,
      delivery_fees: 3.18,
      tax_rate: 0.17,
      taxes: 6.96,
      total: 47.88,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 101,
      reference: "5HPPWJ",
      date: "2020-01-12T11:29:50.522Z",
      customer_id: 387,
      basket: [
        { product_id: 49, quantity: 1 },
        { product_id: 56, quantity: 1 },
      ],
      total_ex_taxes: 94.88,
      delivery_fees: 7.79,
      tax_rate: 0.2,
      taxes: 20.53,
      total: 123.2,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 398,
      reference: "3NMYUV",
      date: "2019-11-20T13:44:34.953Z",
      customer_id: 163,
      basket: [
        { product_id: 92, quantity: 3 },
        { product_id: 103, quantity: 1 },
      ],
      total_ex_taxes: 217.97000000000003,
      delivery_fees: 7.98,
      tax_rate: 0.12,
      taxes: 27.11,
      total: 253.06,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 77,
      reference: "470BJD",
      date: "2019-10-22T15:40:19.248Z",
      customer_id: 172,
      basket: [
        { product_id: 21, quantity: 3 },
        { product_id: 28, quantity: 4 },
      ],
      total_ex_taxes: 262.83000000000004,
      delivery_fees: 5.5,
      tax_rate: 0.17,
      taxes: 45.62,
      total: 313.95,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 417,
      reference: "EDP0UB",
      date: "2019-09-04T02:31:33.850Z",
      customer_id: 68,
      basket: [{ product_id: 32, quantity: 2 }],
      total_ex_taxes: 72.64,
      delivery_fees: 5.21,
      tax_rate: 0.12,
      taxes: 9.34,
      total: 87.19,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 400,
      reference: "OQB2RU",
      date: "2019-08-14T03:33:40.091Z",
      customer_id: 327,
      basket: [
        { product_id: 54, quantity: 2 },
        { product_id: 0, quantity: 2 },
      ],
      total_ex_taxes: 169.32,
      delivery_fees: 7.11,
      tax_rate: 0.17,
      taxes: 29.99,
      total: 206.42,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 250,
      reference: "WB1IG9",
      date: "2019-07-25T23:39:35.323Z",
      customer_id: 31,
      basket: [{ product_id: 121, quantity: 2 }],
      total_ex_taxes: 131.54,
      delivery_fees: 5.96,
      tax_rate: 0.12,
      taxes: 16.5,
      total: 154,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 376,
      reference: "DBDI7V",
      date: "2019-06-22T06:48:23.191Z",
      customer_id: 353,
      basket: [{ product_id: 106, quantity: 2 }],
      total_ex_taxes: 143.72,
      delivery_fees: 6.76,
      tax_rate: 0.12,
      taxes: 18.06,
      total: 168.54,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
    {
      id: 157,
      reference: "W3XF0G",
      date: "2019-05-29T21:43:48.540Z",
      customer_id: 578,
      basket: [
        { product_id: 92, quantity: 1 },
        { product_id: 101, quantity: 1 },
      ],
      total_ex_taxes: 67.95,
      delivery_fees: 5.75,
      tax_rate: 0.12,
      taxes: 8.84,
      total: 82.54,
      status: "cancelled",
      returned: false,
      batch: 0,
    },
  ],
  categories: [
    {
      id: 5,
      name: "categories",
      isRoot: true,
      children: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120],
    },

    { id: 0, name: "animals", isRoot: false, children: [1, 2, 3] },
    { id: 1, name: "cute", isRoot: false, children: [] },
    { id: 2, name: "scary", isRoot: false, children: [] },
    { id: 3, name: "weird", isRoot: false, children: [] },

    { id: 10, name: "beard", isRoot: false, children: [11, 12] },
    { id: 11, name: "curly", isRoot: false, children: [] },
    { id: 12, name: "straight", isRoot: false, children: [] },

    { id: 20, name: "business", isRoot: false, children: [] },

    { id: 30, name: "cars", isRoot: false, children: [31, 32] },
    { id: 31, name: "fast", isRoot: false, children: [] },
    { id: 32, name: "slow", isRoot: false, children: [] },

    { id: 40, name: "city", isRoot: false, children: [] },
    { id: 50, name: "flowers", isRoot: false, children: [] },

    { id: 60, name: "food", isRoot: false, children: [61, 62] },
    { id: 61, name: "liquid", isRoot: false, children: [] },
    { id: 62, name: "solid", isRoot: false, children: [] },

    { id: 70, name: "nature", isRoot: false, children: [] },

    { id: 80, name: "people", isRoot: false, children: [81, 82, 83] },
    { id: 81, name: "one", isRoot: false, children: [] },
    { id: 82, name: "couple", isRoot: false, children: [] },
    { id: 83, name: "many", isRoot: false, children: [] },

    { id: 90, name: "sports", isRoot: false, children: [] },
    { id: 100, name: "tech", isRoot: false, children: [] },
    { id: 110, name: "travel", isRoot: false, children: [] },
    { id: 120, name: "water", isRoot: false, children: [] },
  ],
  products: [
    {
      id: 0,
      category_id: 1,
      reference: "an-589lt-O",
      width: 15.07,
      height: 35.49,
      price: 35.13,
      thumbnail: "https://marmelab.com/posters/animals-1.jpeg",
      image: "https://marmelab.com/posters/animals-1.jpeg",
      description:
        "Molestias aut repudiandae neque in deserunt veniam iusto. Ut esse occaecati corrupti dolore numquam dolorem. Ex amet labore in ducimus quas quisquam qui architecto voluptas. Ad eius et deleniti voluptatem iusto sed provident. Omnis rerum ut cum consectetur quia placeat.",
      stock: 62,
    },
    {
      id: 1,
      category_id: 1,
      reference: "an-xuh1c-F",
      width: 32.54,
      height: 31.14,
      price: 50.8,
      thumbnail: "https://marmelab.com/posters/animals-2.jpeg",
      image: "https://marmelab.com/posters/animals-2.jpeg",
      description:
        "Eaque doloribus molestiae cupiditate totam inventore minus. Officia voluptate qui quisquam totam et nam odit consequatur iusto. Non enim vero eius aut fugit eos unde. Quae est omnis dolorem officiis quia omnis nesciunt voluptatem occaecati. Quo nihil impedit laudantium repudiandae doloremque a quidem.",
      stock: 36,
    },
    {
      id: 2,
      category_id: 3,
      reference: "an-0qr5a-N",
      width: 39.41,
      height: 22.12,
      price: 55.46,
      thumbnail: "https://marmelab.com/posters/animals-3.jpeg",
      image: "https://marmelab.com/posters/animals-3.jpeg",
      description:
        "Quam qui omnis reprehenderit harum cumque eos voluptas quia suscipit. Labore amet soluta cum quo fugit quia placeat. Eos et est consequatur enim eum qui atque et.",
      stock: 92,
    },
    {
      id: 3,
      category_id: 2,
      reference: "an-7yzqw-F",
      width: 38.8,
      height: 39.16,
      price: 93.11,
      thumbnail: "https://marmelab.com/posters/animals-4.jpeg",
      image: "https://marmelab.com/posters/animals-4.jpeg",
      description:
        "Aspernatur quo perferendis qui corporis. Totam rerum porro commodi similique quam et omnis fuga. Excepturi magnam modi velit hic est soluta aut quibusdam.",
      stock: 177,
    },
    {
      id: 4,
      category_id: 1,
      reference: "an-l0p1z-Y",
      width: 37.21,
      height: 27.97,
      price: 62.28,
      thumbnail: "https://marmelab.com/posters/animals-5.jpeg",
      image: "https://marmelab.com/posters/animals-5.jpeg",
      description:
        "Voluptatibus sed nulla. Non architecto nam ipsa dolores quaerat. Iste provident est dolorem enim saepe suscipit aperiam dolorem.",
      stock: 216,
    },
    {
      id: 5,
      category_id: 3,
      reference: "an-j98hn-A",
      width: 36.71,
      height: 28.17,
      price: 59.6,
      thumbnail: "https://marmelab.com/posters/animals-6.jpeg",
      image: "https://marmelab.com/posters/animals-6.jpeg",
      description:
        "Possimus esse sint repellat non. Ducimus beatae facilis nemo dolore voluptate. Animi tempore minus sequi libero impedit eum rem.",
      stock: 9,
    },
    {
      id: 6,
      category_id: 1,
      reference: "an-vp43s-G",
      width: 29.47,
      height: 15.02,
      price: 29.48,
      thumbnail: "https://marmelab.com/posters/animals-7.jpeg",
      image: "https://marmelab.com/posters/animals-7.jpeg",
      description:
        "Officiis quidem nihil quisquam. Consequatur ab et eos. Consectetur dignissimos et et nesciunt dolorem distinctio. Nihil iusto facere debitis pariatur. Impedit perspiciatis et facere rem sint. Quaerat et fugiat voluptatem nemo repellat.",
      stock: 144,
    },
    {
      id: 7,
      category_id: 2,
      reference: "an-rsnyx-Y",
      width: 15.97,
      height: 28.92,
      price: 25.47,
      thumbnail: "https://marmelab.com/posters/animals-8.jpeg",
      image: "https://marmelab.com/posters/animals-8.jpeg",
      description:
        "Sed delectus suscipit dolore omnis illum inventore ullam molestiae. Natus sed et molestiae. Officiis maxime quibusdam animi voluptatem cum est. Veritatis minima libero temporibus molestias expedita expedita. Soluta quo nam quasi. Corporis assumenda culpa.",
      stock: 125,
    },
    {
      id: 8,
      category_id: 3,
      reference: "an-l2ozz-Q",
      width: 12.12,
      height: 35.94,
      price: 28.85,
      thumbnail: "https://marmelab.com/posters/animals-9.jpeg",
      image: "https://marmelab.com/posters/animals-9.jpeg",
      description:
        "Consequuntur eos illo eos sint. Voluptatem voluptas velit omnis magni suscipit provident. Aliquid ea laborum enim explicabo dolores impedit. Velit eum non molestias enim eos similique exercitationem ratione. Illum repellendus vero.",
      stock: 233,
    },
    {
      id: 9,
      category_id: 3,
      reference: "an-8ih5d-I",
      width: 25.36,
      height: 18.28,
      price: 27.92,
      thumbnail: "https://marmelab.com/posters/animals-10.jpeg",
      image: "https://marmelab.com/posters/animals-10.jpeg",
      description:
        "Atque ex repudiandae aut. Qui aperiam iusto. Enim non ipsam voluptatibus et. Et modi earum eum cupiditate sit consequatur eveniet. Perspiciatis architecto consequatur autem eum.",
      stock: 146,
    },
    //beard
    {
      id: 10,
      category_id: 12,
      reference: "be-7a22w-L",
      width: 35.81,
      height: 12.23,
      price: 22.32,
      thumbnail: "https://marmelab.com/posters/beard-1.jpeg",
      image: "https://marmelab.com/posters/beard-1.jpeg",
      description:
        "Quisquam consequatur a recusandae repellat quia unde dolore. Fugiat velit voluptas. Sunt sed exercitationem. Ipsam ipsam et animi quae eum beatae. Ut aut voluptatum quaerat et animi.",
      stock: 0,
    },
    {
      id: 11,
      category_id: 11,
      reference: "be-5ywhw-B",
      width: 18.99,
      height: 25.35,
      price: 28.38,
      thumbnail: "https://marmelab.com/posters/beard-2.jpeg",
      image: "https://marmelab.com/posters/beard-2.jpeg",
      description:
        "Velit eos excepturi eum deserunt asperiores impedit. Voluptatum aut ea ea pariatur provident similique. Eius ea nesciunt culpa sunt itaque maxime rerum a. Similique consequatur quidem eum esse consequatur laborum est aut nihil.",
      stock: 69,
    },
    {
      id: 12,
      category_id: 11,
      reference: "be-lnbs4-T",
      width: 22.2,
      height: 32.36,
      price: 37.31,
      thumbnail: "https://marmelab.com/posters/beard-3.jpeg",
      image: "https://marmelab.com/posters/beard-3.jpeg",
      description:
        "Eaque delectus possimus laudantium et tempore. Libero minus vitae unde voluptatem. Quos omnis natus praesentium labore. Illo ut enim deleniti quasi totam recusandae.",
      stock: 114,
    },
    {
      id: 13,
      category_id: 12,
      reference: "be-7ad0p-J",
      width: 29.4,
      height: 10.89,
      price: 16.22,
      thumbnail: "https://marmelab.com/posters/beard-4.jpeg",
      image: "https://marmelab.com/posters/beard-4.jpeg",
      description:
        "Debitis nam doloribus nemo quia eum. Architecto ducimus nemo. Suscipit distinctio aut alias illo labore soluta quisquam. Error corporis incidunt. Labore iusto iure inventore non.",
      stock: 19,
    },
    {
      id: 14,
      category_id: 12,
      reference: "be-0q74n-N",
      width: 14.05,
      height: 38.14,
      price: 34.5,
      thumbnail: "https://marmelab.com/posters/beard-5.jpeg",
      image: "https://marmelab.com/posters/beard-5.jpeg",
      description:
        "Voluptatibus tenetur non et. Error totam illo eveniet distinctio iste et libero aut. Laborum vitae sapiente omnis id aut quis provident ullam possimus. Rerum non sed sequi. Aperiam animi voluptas quis et commodi officiis.",
      stock: 11,
    },
    {
      id: 15,
      category_id: 12,
      reference: "be-c9lzv-S",
      width: 27.43,
      height: 17.45,
      price: 25.35,
      thumbnail: "https://marmelab.com/posters/beard-6.jpeg",
      image: "https://marmelab.com/posters/beard-6.jpeg",
      description:
        "Voluptatem necessitatibus quasi animi. Officia doloremque exercitationem. Aut dolorem id blanditiis.",
      stock: 52,
    },
    {
      id: 16,
      category_id: 11,
      reference: "be-bhlzh-P",
      width: 39.99,
      height: 34.36,
      price: 71.41,
      thumbnail: "https://marmelab.com/posters/beard-7.jpeg",
      image: "https://marmelab.com/posters/beard-7.jpeg",
      description:
        "Minus ipsam non accusantium voluptatem eaque aut enim. Sequi laboriosam ab. Dolor architecto sed placeat accusantium sed illum et consequatur temporibus. Qui et aliquid corrupti assumenda.",
      stock: 10,
    },
    {
      id: 17,
      category_id: 11,
      reference: "be-nr737-D",
      width: 34.43,
      height: 32.11,
      price: 56.34,
      thumbnail: "https://marmelab.com/posters/beard-8.jpeg",
      image: "https://marmelab.com/posters/beard-8.jpeg",
      description:
        "Eum et voluptatem deserunt et sed laboriosam nam. Iure qui voluptas molestiae sint velit est dicta fugit. Voluptatem deleniti vel sint magni officiis. Ut id sed deleniti consequuntur sed eos nesciunt. Fugit consequatur rem dolore reprehenderit est. Sed molestiae tenetur ratione.",
      stock: 85,
    },
    {
      id: 18,
      category_id: 12,
      reference: "be-uciql-M",
      width: 19.07,
      height: 29.43,
      price: 30.44,
      thumbnail: "https://marmelab.com/posters/beard-9.jpeg",
      image: "https://marmelab.com/posters/beard-9.jpeg",
      description:
        "Ipsum maxime hic asperiores. Voluptate ipsam nam deleniti. Et voluptas voluptas. Perspiciatis iusto provident fugiat quisquam et. Aut sed laudantium voluptatem iusto necessitatibus minus et magni totam. Excepturi iste ducimus.",
      stock: 245,
    },
    {
      id: 19,
      category_id: 12,
      reference: "be-m133t-Z",
      width: 39.31,
      height: 29.34,
      price: 69.31,
      thumbnail: "https://marmelab.com/posters/beard-10.jpeg",
      image: "https://marmelab.com/posters/beard-10.jpeg",
      description:
        "Ipsum est dolorum et beatae beatae inventore vero qui. Sunt ad minus soluta sit voluptatum. Beatae ipsum eveniet natus dolorum. Exercitationem quo dolor. Velit ex occaecati voluptate et praesentium.",
      stock: 37,
    },
    // business
    {
      id: 20,
      category_id: 20,
      reference: "bu-g2ng5-T",
      width: 29.3,
      height: 25.39,
      price: 42.01,
      thumbnail: "https://marmelab.com/posters/business-1.jpeg",
      image: "https://marmelab.com/posters/business-1.jpeg",
      description:
        "Est laborum qui iure omnis. Quos et expedita accusantium dolores ad et illum. Possimus molestiae et ratione voluptate esse. Nam sunt et et sint est ad cumque omnis qui. In et ipsam alias qui ratione. Sit aspernatur quo similique.",
      stock: 22,
    },
    {
      id: 21,
      category_id: 20,
      reference: "bu-h047x-J",
      width: 16.44,
      height: 39.39,
      price: 40.76,
      thumbnail: "https://marmelab.com/posters/business-2.jpeg",
      image: "https://marmelab.com/posters/business-2.jpeg",
      description:
        "Voluptatem tempore sequi esse officia inventore tempore unde et et. Totam illum explicabo et quis voluptate sunt. Vel explicabo accusamus.",
      stock: 95,
    },
    {
      id: 22,
      category_id: 20,
      reference: "bu-yd1jd-B",
      width: 23.97,
      height: 25.62,
      price: 32.66,
      thumbnail: "https://marmelab.com/posters/business-3.jpeg",
      image: "https://marmelab.com/posters/business-3.jpeg",
      description:
        "Et quaerat accusamus optio itaque. Nisi voluptatem ut repellendus optio adipisci. Soluta enim rerum quisquam unde commodi corrupti aperiam amet et.",
      stock: 177,
    },
    {
      id: 23,
      category_id: 20,
      reference: "bu-fh4l9-S",
      width: 25.07,
      height: 27.73,
      price: 41.28,
      thumbnail: "https://marmelab.com/posters/business-4.jpeg",
      image: "https://marmelab.com/posters/business-4.jpeg",
      description:
        "Quo quos quam voluptas autem earum nobis vero architecto ad. Quibusdam et necessitatibus esse quas non ipsa quas consequatur quia. Vel suscipit distinctio eum velit ut ex. Harum quidem adipisci iusto saepe rerum enim dolor reiciendis veniam. Facilis voluptas ut officia cumque explicabo quia corrupti natus. Veniam laboriosam odit non et ut cum mollitia.",
      stock: 109,
    },
    {
      id: 24,
      category_id: 20,
      reference: "bu-0v2zl-O",
      width: 27.69,
      height: 28.38,
      price: 44.13,
      thumbnail: "https://marmelab.com/posters/business-5.jpeg",
      image: "https://marmelab.com/posters/business-5.jpeg",
      description:
        "Et adipisci et dolorem blanditiis minus explicabo. Expedita eos molestiae quo. Accusamus deserunt ipsum et. Et asperiores occaecati et. Eligendi deleniti alias provident.",
      stock: 97,
    },
    {
      id: 25,
      category_id: 20,
      reference: "bu-emckg-K",
      width: 10.89,
      height: 10.87,
      price: 6.69,
      thumbnail: "https://marmelab.com/posters/business-6.jpeg",
      image: "https://marmelab.com/posters/business-6.jpeg",
      description:
        "Saepe non rerum voluptatem cumque ipsum aut autem. Quia est porro et explicabo rem corporis exercitationem molestiae. Dolor laboriosam eveniet sunt id laboriosam. Et veritatis alias quisquam pariatur nobis nisi voluptatibus. Adipisci unde enim magnam accusamus.",
      stock: 8,
    },
    {
      id: 26,
      category_id: 20,
      reference: "bu-0o0gw-Q",
      width: 39.88,
      height: 14.95,
      price: 35.32,
      thumbnail: "https://marmelab.com/posters/business-7.jpeg",
      image: "https://marmelab.com/posters/business-7.jpeg",
      description:
        "Minima quia sint voluptas sapiente assumenda et blanditiis. Non eligendi qui pariatur dolor officia. Accusantium ea quis ut ullam rerum quia.",
      stock: 119,
    },
    {
      id: 27,
      category_id: 20,
      reference: "bu-cas8t-D",
      width: 11.27,
      height: 25.77,
      price: 18.36,
      thumbnail: "https://marmelab.com/posters/business-8.jpeg",
      image: "https://marmelab.com/posters/business-8.jpeg",
      description:
        "Et sit ut asperiores deleniti. Id enim non vel quia eos expedita. Et cum aliquid quia mollitia. Odit eaque quasi asperiores. Sit pariatur voluptas voluptatibus et. Voluptatem eveniet molestias laudantium omnis et.",
      stock: 23,
    },
    {
      id: 28,
      category_id: 20,
      reference: "bu-bcqsl-W",
      width: 24.59,
      height: 19.48,
      price: 27.4,
      thumbnail: "https://marmelab.com/posters/business-9.jpeg",
      image: "https://marmelab.com/posters/business-9.jpeg",
      description:
        "Incidunt id officiis dolores atque quia. Non ratione quibusdam quo qui harum recusandae sed. Qui fugit eius neque error nostrum est et unde. Perspiciatis quos rerum. Nesciunt atque dicta.",
      stock: 125,
    },
    {
      id: 29,
      category_id: 20,
      reference: "bu-xkwwh-K",
      width: 37.34,
      height: 10.65,
      price: 25.29,
      thumbnail: "https://marmelab.com/posters/business-10.jpeg",
      image: "https://marmelab.com/posters/business-10.jpeg",
      description:
        "Dolore qui pariatur et facere enim veritatis animi praesentium. Quia neque voluptas repellat. Qui eius nam aperiam aliquid. Et eius ipsam aut asperiores.",
      stock: 121,
    },
    // cars
    {
      id: 30,
      category_id: 32,
      reference: "ca-9aqcq-F",
      width: 21.75,
      height: 12.56,
      price: 18.02,
      thumbnail: "https://marmelab.com/posters/cars-1.jpeg",
      image: "https://marmelab.com/posters/cars-1.jpeg",
      description:
        "Harum placeat mollitia enim et. Iusto necessitatibus laborum dolor distinctio expedita provident dolorum. Esse aut ea iure iste laudantium.",
      stock: 96,
    },
    {
      id: 31,
      category_id: 32,
      reference: "ca-aguhv-Y",
      width: 29.78,
      height: 29.32,
      price: 53.76,
      thumbnail: "https://marmelab.com/posters/cars-2.jpeg",
      image: "https://marmelab.com/posters/cars-2.jpeg",
      description:
        "Et ut et facilis sequi odio quod eum. Fuga totam atque qui cumque quam. Porro quibusdam eius officiis et eius consequatur deserunt tempore occaecati.",
      stock: 146,
    },
    {
      id: 32,
      category_id: 32,
      reference: "ca-hot6v-Y",
      width: 14.73,
      height: 32.01,
      price: 31.03,
      thumbnail: "https://marmelab.com/posters/cars-3.jpeg",
      image: "https://marmelab.com/posters/cars-3.jpeg",
      description:
        "Nostrum perferendis ab praesentium beatae veniam. Ut vel quos omnis nam dicta voluptas et dolorem earum. Et neque itaque rerum enim. Facilis voluptatem a officia quo blanditiis sint sint rerum. Itaque nostrum magni consequatur vitae saepe.",
      stock: 118,
    },
    {
      id: 33,
      category_id: 32,
      reference: "ca-c503o-K",
      width: 11.86,
      height: 36.72,
      price: 23.16,
      thumbnail: "https://marmelab.com/posters/cars-4.jpeg",
      image: "https://marmelab.com/posters/cars-4.jpeg",
      description:
        "Perspiciatis et consequuntur est corrupti molestias neque repudiandae est quaerat. Quibusdam qui debitis nobis mollitia et. Adipisci voluptatem sint. Tenetur veniam natus doloremque unde. Ea sit blanditiis illo.",
      stock: 116,
    },
    {
      id: 34,
      category_id: 31,
      reference: "ca-zeo3j-O",
      width: 19.28,
      height: 29.79,
      price: 32.77,
      thumbnail: "https://marmelab.com/posters/cars-5.jpeg",
      image: "https://marmelab.com/posters/cars-5.jpeg",
      description:
        "Consequatur at est dolor ex sint quisquam et velit optio. Quia rerum aspernatur veniam ad iusto optio. Iure velit iste similique ab optio assumenda. Porro aut aut sapiente qui. Labore illum nisi labore deleniti.",
      stock: 170,
    },
    {
      id: 35,
      category_id: 32,
      reference: "ca-kgqe8-L",
      width: 38.71,
      height: 23.73,
      price: 50.2,
      thumbnail: "https://marmelab.com/posters/cars-6.jpeg",
      image: "https://marmelab.com/posters/cars-6.jpeg",
      description:
        "Quidem minus deleniti rerum doloribus saepe beatae laboriosam. Aspernatur delectus quo. Ipsam fuga at quae consectetur illum sed.",
      stock: 0,
    },
    {
      id: 36,
      category_id: 32,
      reference: "ca-ttk2r-S",
      width: 22.96,
      height: 15.05,
      price: 18.94,
      thumbnail: "https://marmelab.com/posters/cars-7.jpeg",
      image: "https://marmelab.com/posters/cars-7.jpeg",
      description:
        "Necessitatibus eius qui aut nesciunt perferendis. Quidem qui optio rerum. Ea voluptatum laudantium doloribus est. Eum dolor amet ipsa veritatis iusto repellendus. Cum ut omnis neque nihil id enim asperiores in.",
      stock: 0,
    },
    {
      id: 37,
      category_id: 31,
      reference: "ca-oisxb-F",
      width: 14.72,
      height: 36.76,
      price: 33.59,
      thumbnail: "https://marmelab.com/posters/cars-8.jpeg",
      image: "https://marmelab.com/posters/cars-8.jpeg",
      description:
        "Perspiciatis aliquam voluptatum optio aut blanditiis ducimus magni enim voluptas. Natus omnis architecto recusandae a tenetur facilis. Quas occaecati cupiditate nam dicta deleniti excepturi. Sint facilis suscipit possimus.",
      stock: 0,
    },
    {
      id: 38,
      category_id: 31,
      reference: "ca-awok9-W",
      width: 18.48,
      height: 15.77,
      price: 19.02,
      thumbnail: "https://marmelab.com/posters/cars-9.jpeg",
      image: "https://marmelab.com/posters/cars-9.jpeg",
      description:
        "Quod ratione voluptas vero asperiores. Consequuntur voluptatem quos. Delectus velit consequuntur ullam dolorem. Officia et veniam architecto ut et. Doloremque facilis cumque laudantium et.",
      stock: 116,
    },
    {
      id: 39,
      category_id: 31,
      reference: "ca-bcx48-G",
      width: 35.27,
      height: 30.33,
      price: 68.61,
      thumbnail: "https://marmelab.com/posters/cars-10.jpeg",
      image: "https://marmelab.com/posters/cars-10.jpeg",
      description:
        "Praesentium quaerat non corporis. Voluptatum quia deserunt omnis. Est aut voluptatem veniam eligendi error nesciunt soluta impedit eius.",
      stock: 232,
    },
    // cities
    {
      id: 40,
      category_id: 40,
      reference: "ci-uxqkq-M",
      width: 24.32,
      height: 13.83,
      price: 19.98,
      thumbnail: "https://marmelab.com/posters/city-1.jpeg",
      image: "https://marmelab.com/posters/city-1.jpeg",
      description:
        "Voluptatem earum labore mollitia molestiae. Nostrum veritatis dolore tempora quae. Qui totam sit et. Unde natus accusamus enim non est sint eum.",
      stock: 14,
    },
    {
      id: 41,
      category_id: 40,
      reference: "ci-q707t-Q",
      width: 29.17,
      height: 24.81,
      price: 45.89,
      thumbnail: "https://marmelab.com/posters/city-2.jpeg",
      image: "https://marmelab.com/posters/city-2.jpeg",
      description:
        "Repudiandae rerum enim earum veritatis atque sunt aut doloremque dolor. Nulla nobis qui et alias ut consequatur. Et quo exercitationem. Natus mollitia et cum inventore reiciendis labore et et.",
      stock: 0,
    },
    {
      id: 42,
      category_id: 40,
      reference: "ci-x8oqk-K",
      width: 15.43,
      height: 29.88,
      price: 29.96,
      thumbnail: "https://marmelab.com/posters/city-3.jpeg",
      image: "https://marmelab.com/posters/city-3.jpeg",
      description:
        "Et quia voluptatem repellat et autem ut qui. Est atque aliquam. Voluptatem ipsa veritatis enim enim. Aperiam praesentium sint vitae excepturi. Occaecati nemo beatae quis et sint ratione quod rerum est.",
      stock: 119,
    },
    {
      id: 43,
      category_id: 40,
      reference: "ci-6k1qn-D",
      width: 32.68,
      height: 20.99,
      price: 35.06,
      thumbnail: "https://marmelab.com/posters/city-4.jpeg",
      image: "https://marmelab.com/posters/city-4.jpeg",
      description:
        "Accusamus aperiam velit neque ea laborum facere tempore corrupti ipsam. Optio ab veritatis illo suscipit provident illo voluptas. Facilis eos consequatur voluptatibus mollitia similique ipsa velit. Veritatis harum modi possimus voluptatibus suscipit sit mollitia id. Aut dolores qui blanditiis eaque quia laudantium reprehenderit voluptates. Eum voluptatum quia illum harum aut ratione.",
      stock: 137,
    },
    {
      id: 44,
      category_id: 40,
      reference: "ci-ty4rh-G",
      width: 16.76,
      height: 27.89,
      price: 27.02,
      thumbnail: "https://marmelab.com/posters/city-5.jpeg",
      image: "https://marmelab.com/posters/city-5.jpeg",
      description:
        "Amet et ab enim id. Eum quaerat alias nesciunt repellendus quae. Ea dolores eos ipsa ea quam et perspiciatis.",
      stock: 103,
    },
    {
      id: 45,
      category_id: 40,
      reference: "ci-idtgp-A",
      width: 27.46,
      height: 36.4,
      price: 63.6,
      thumbnail: "https://marmelab.com/posters/city-6.jpeg",
      image: "https://marmelab.com/posters/city-6.jpeg",
      description:
        "Dolorem et eos et quo quia aut atque. Aspernatur atque ea totam ex qui. Amet quia iste vel pariatur vel consequatur quis. Error officiis voluptatibus architecto consequatur. Molestiae est sed aut iure possimus maxime porro.",
      stock: 116,
    },
    {
      id: 46,
      category_id: 40,
      reference: "ci-469i3-W",
      width: 19.97,
      height: 34.01,
      price: 41.12,
      thumbnail: "https://marmelab.com/posters/city-7.jpeg",
      image: "https://marmelab.com/posters/city-7.jpeg",
      description:
        "Voluptates rerum molestiae sit veritatis consequatur accusantium. Consequuntur dignissimos incidunt. Autem voluptatem labore rerum dicta.",
      stock: 169,
    },
    {
      id: 47,
      category_id: 40,
      reference: "ci-7vpsf-J",
      width: 38.89,
      height: 37.46,
      price: 92.63,
      thumbnail: "https://marmelab.com/posters/city-8.jpeg",
      image: "https://marmelab.com/posters/city-8.jpeg",
      description:
        "Et quasi rem praesentium consequatur cupiditate libero dignissimos placeat. Itaque nostrum atque qui excepturi corrupti. Est harum quam enim officia. Voluptatem dolorem ipsum voluptate. Enim tempore et et voluptatibus non. Ea cupiditate sint et numquam.",
      stock: 249,
    },
    {
      id: 48,
      category_id: 40,
      reference: "ci-da0x7-D",
      width: 34.88,
      height: 17.14,
      price: 38.12,
      thumbnail: "https://marmelab.com/posters/city-9.jpeg",
      image: "https://marmelab.com/posters/city-9.jpeg",
      description:
        "Dolore qui vitae sit error dolorem corporis laborum vel. Consequatur ea officia dolor. Quia dolorem quia ut et expedita corrupti animi fugiat. Facere laudantium distinctio.",
      stock: 71,
    },
    {
      id: 49,
      category_id: 40,
      reference: "ci-a1yag-J",
      width: 14.87,
      height: 31.78,
      price: 28.34,
      thumbnail: "https://marmelab.com/posters/city-10.jpeg",
      image: "https://marmelab.com/posters/city-10.jpeg",
      description:
        "Voluptatem quam ex voluptate ad sint quibusdam adipisci commodi voluptatem. Enim ut nihil harum doloremque dolorem rerum voluptatibus cumque velit. Expedita qui aut.",
      stock: 147,
    },
    // flowers
    {
      id: 50,
      category_id: 50,
      reference: "fl-lnwvx-Y",
      width: 22.55,
      height: 13.88,
      price: 18.23,
      thumbnail: "https://marmelab.com/posters/flowers-1.jpeg",
      image: "https://marmelab.com/posters/flowers-1.jpeg",
      description:
        "Provident blanditiis quia maxime ipsam perspiciatis vel est vel exercitationem. Quaerat assumenda aliquid non reprehenderit dolore ratione minus sint minima. Officia dicta aperiam enim maxime fugit sint. Modi ut similique illo aut dignissimos vel non cupiditate sint.",
      stock: 40,
    },
    {
      id: 51,
      category_id: 50,
      reference: "fl-hehrh-Q",
      width: 27.84,
      height: 11.56,
      price: 17.3,
      thumbnail: "https://marmelab.com/posters/flowers-2.jpeg",
      image: "https://marmelab.com/posters/flowers-2.jpeg",
      description:
        "Optio in in quos ipsa sit. Minus doloribus quam inventore laborum. Totam suscipit quisquam. Sint cupiditate ad sunt natus saepe excepturi omnis accusamus. Nisi quaerat natus.",
      stock: 0,
    },
    {
      id: 52,
      category_id: 50,
      reference: "fl-xe7lk-A",
      width: 31.13,
      height: 11.61,
      price: 22,
      thumbnail: "https://marmelab.com/posters/flowers-3.jpeg",
      image: "https://marmelab.com/posters/flowers-3.jpeg",
      description:
        "Et nemo aut voluptas et et sequi itaque voluptatibus. Eos unde id ab. Ab qui qui ut excepturi molestiae unde. Consequatur omnis vero vitae nostrum harum cum et. Et consectetur dolores quibusdam expedita qui tempora eos sint.",
      stock: 51,
    },
    {
      id: 53,
      category_id: 50,
      reference: "fl-tpls8-N",
      width: 17.77,
      height: 34.36,
      price: 31.54,
      thumbnail: "https://marmelab.com/posters/flowers-4.jpeg",
      image: "https://marmelab.com/posters/flowers-4.jpeg",
      description:
        "Delectus aut deserunt excepturi non. Inventore qui vel quis dolores culpa. Est dolores et laudantium. Culpa ea maiores ipsa placeat facere magnam porro. Eaque iste esse laborum ab inventore tempore. Ut rem voluptatibus ratione.",
      stock: 168,
    },
    {
      id: 54,
      category_id: 50,
      reference: "fl-a990m-N",
      width: 13.2,
      height: 23.53,
      price: 18.62,
      thumbnail: "https://marmelab.com/posters/flowers-5.jpeg",
      image: "https://marmelab.com/posters/flowers-5.jpeg",
      description:
        "Et impedit amet at perferendis est ut. Accusamus rerum hic quaerat. Odio officiis tempora distinctio voluptas consequatur fugit.",
      stock: 188,
    },
    {
      id: 55,
      category_id: 50,
      reference: "fl-dks1a-J",
      width: 35.43,
      height: 30.2,
      price: 66.61,
      thumbnail: "https://marmelab.com/posters/flowers-6.jpeg",
      image: "https://marmelab.com/posters/flowers-6.jpeg",
      description:
        "Eum nemo unde culpa. Hic praesentium sed molestiae illo veniam molestiae quia quasi. Et reiciendis et.",
      stock: 0,
    },
    {
      id: 56,
      category_id: 50,
      reference: "fl-a03fx-P",
      width: 23.34,
      height: 14.61,
      price: 18.89,
      thumbnail: "https://marmelab.com/posters/flowers-7.jpeg",
      image: "https://marmelab.com/posters/flowers-7.jpeg",
      description:
        "Qui voluptas non blanditiis nulla veniam. Laborum consequatur sit. Sed debitis voluptas.",
      stock: 0,
    },
    {
      id: 57,
      category_id: 50,
      reference: "fl-3xyl5-V",
      width: 25.13,
      height: 28.47,
      price: 39.11,
      thumbnail: "https://marmelab.com/posters/flowers-8.jpeg",
      image: "https://marmelab.com/posters/flowers-8.jpeg",
      description:
        "Maxime iste mollitia consequatur expedita sed. Omnis quia velit labore tenetur quia ea fugiat. Qui incidunt molestiae minima similique voluptas.",
      stock: 0,
    },
    {
      id: 58,
      category_id: 50,
      reference: "fl-mjox0-R",
      width: 15.04,
      height: 13.69,
      price: 11.9,
      thumbnail: "https://marmelab.com/posters/flowers-9.jpeg",
      image: "https://marmelab.com/posters/flowers-9.jpeg",
      description:
        "Ea porro et ab et. Aut et illo iure. Incidunt maiores blanditiis quia sit. Dolores sed expedita ut animi architecto eos asperiores voluptatem. Atque nulla quo aut quos dicta quasi.",
      stock: 0,
    },
    {
      id: 59,
      category_id: 50,
      reference: "fl-caoel-Y",
      width: 30.66,
      height: 13.02,
      price: 20.06,
      thumbnail: "https://marmelab.com/posters/flowers-10.jpeg",
      image: "https://marmelab.com/posters/flowers-10.jpeg",
      description:
        "Vel nostrum labore quas officia voluptas rerum magni. Architecto sint possimus eius blanditiis sapiente quidem et. Recusandae illo eligendi commodi possimus iste qui. Soluta molestiae iure sapiente.",
      stock: 0,
    },
    // food
    {
      id: 60,
      category_id: 62,
      reference: "fo-y8r2j-C",
      width: 12.67,
      height: 25.7,
      price: 20.52,
      thumbnail: "https://marmelab.com/posters/food-1.jpeg",
      image: "https://marmelab.com/posters/food-1.jpeg",
      description:
        "Qui voluptate molestiae labore aut accusamus assumenda. Voluptas aut aut qui ut fugit consequuntur nemo vero sequi. Quam nulla omnis sequi magnam numquam et sint.",
      stock: 23,
    },
    {
      id: 61,
      category_id: 61,
      reference: "fo-5sivx-Q",
      width: 36.01,
      height: 28.81,
      price: 62.73,
      thumbnail: "https://marmelab.com/posters/food-2.jpeg",
      image: "https://marmelab.com/posters/food-2.jpeg",
      description:
        "Quisquam qui iste velit id qui. Sunt velit aliquam iure aut. Doloremque at deleniti molestiae praesentium molestiae.",
      stock: 182,
    },
    {
      id: 62,
      category_id: 61,
      reference: "fo-exoky-B",
      width: 37.73,
      height: 37.16,
      price: 89.72,
      thumbnail: "https://marmelab.com/posters/food-3.jpeg",
      image: "https://marmelab.com/posters/food-3.jpeg",
      description:
        "Temporibus omnis non omnis aliquam pariatur. Rerum hic totam. Et sit occaecati quisquam. Autem consequatur laudantium eum doloremque ducimus et nulla culpa in.",
      stock: 121,
    },
    {
      id: 63,
      category_id: 61,
      reference: "fo-477cl-N",
      width: 26.96,
      height: 11.75,
      price: 20.72,
      thumbnail: "https://marmelab.com/posters/food-4.jpeg",
      image: "https://marmelab.com/posters/food-4.jpeg",
      description:
        "Voluptatem harum cum qui. Asperiores ut beatae aliquam. Ad veniam fugit. Quia expedita iure quae eaque a voluptates.",
      stock: 50,
    },
    {
      id: 64,
      category_id: 62,
      reference: "fo-ml17q-M",
      width: 27.18,
      height: 36.84,
      price: 63.79,
      thumbnail: "https://marmelab.com/posters/food-5.jpeg",
      image: "https://marmelab.com/posters/food-5.jpeg",
      description:
        "Aliquam et suscipit. Esse illo corrupti et numquam sunt ut est. Enim nemo excepturi vero reprehenderit quidem consequatur tenetur consequatur. Nihil omnis vel modi dicta illo et cupiditate esse. Culpa quasi maiores perferendis tempore est aut asperiores.",
      stock: 15,
    },
    {
      id: 65,
      category_id: 62,
      reference: "fo-ag5yg-L",
      width: 26.03,
      height: 14.57,
      price: 20.91,
      thumbnail: "https://marmelab.com/posters/food-6.jpeg",
      image: "https://marmelab.com/posters/food-6.jpeg",
      description:
        "Voluptatum nulla libero vel quo sed. Doloremque dolor voluptatem laboriosam minima doloremque sit dolor. Provident qui temporibus dolores reprehenderit exercitationem voluptates magni iusto. Praesentium aut aut et consequatur et accusantium velit odit.",
      stock: 72,
    },
    {
      id: 66,
      category_id: 61,
      reference: "fo-9ci6p-T",
      width: 32.55,
      height: 28.41,
      price: 49.34,
      thumbnail: "https://marmelab.com/posters/food-7.jpeg",
      image: "https://marmelab.com/posters/food-7.jpeg",
      description:
        "Corporis est provident exercitationem iste. Ullam aut et suscipit et eum ea qui veniam. Aut dolorem voluptatem accusantium.",
      stock: 93,
    },
    {
      id: 67,
      category_id: 61,
      reference: "fo-tzo3e-P",
      width: 18.28,
      height: 17.68,
      price: 21.12,
      thumbnail: "https://marmelab.com/posters/food-8.jpeg",
      image: "https://marmelab.com/posters/food-8.jpeg",
      description:
        "Eveniet maiores omnis beatae dolore qui. Animi et tempora dignissimos asperiores rem nihil voluptas. Cumque veniam eligendi nihil eos rem voluptatibus.",
      stock: 166,
    },
    {
      id: 68,
      category_id: 62,
      reference: "fo-fel34-U",
      width: 26.24,
      height: 18.08,
      price: 26.36,
      thumbnail: "https://marmelab.com/posters/food-9.jpeg",
      image: "https://marmelab.com/posters/food-9.jpeg",
      description:
        "Ea quo dolores eum molestiae quia doloribus. Quo corrupti reprehenderit quod est omnis modi et perspiciatis tempore. Inventore sunt omnis aut quibusdam molestiae est quo deserunt.",
      stock: 197,
    },
    {
      id: 69,
      category_id: 61,
      reference: "fo-k8lj8-P",
      width: 10.66,
      height: 19.57,
      price: 12.55,
      thumbnail: "https://marmelab.com/posters/food-10.jpeg",
      image: "https://marmelab.com/posters/food-10.jpeg",
      description:
        "Sapiente molestiae quibusdam itaque et eaque iusto modi illo quas. Inventore deleniti sapiente explicabo aliquid. Magnam ducimus veritatis ullam voluptatibus eligendi esse.",
      stock: 2,
    },
    // nature
    {
      id: 70,
      category_id: 70,
      reference: "na-vh25f-Q",
      width: 13.3,
      height: 22.82,
      price: 18.73,
      thumbnail: "https://marmelab.com/posters/nature-1.jpeg",
      image: "https://marmelab.com/posters/nature-1.jpeg",
      description:
        "Excepturi et ab ut sed commodi praesentium quos eligendi. Nostrum sit facere minima. Ut placeat qui perferendis suscipit enim et deserunt dicta dolor. Ut soluta culpa unde. At quia eligendi non perferendis. Placeat eum molestias et excepturi quia magnam quia tenetur non.",
      stock: 0,
    },
    {
      id: 71,
      category_id: 70,
      reference: "na-e61nr-W",
      width: 25.26,
      height: 15.42,
      price: 22.74,
      thumbnail: "https://marmelab.com/posters/nature-2.jpeg",
      image: "https://marmelab.com/posters/nature-2.jpeg",
      description:
        "Unde alias cumque consequuntur at distinctio nihil nemo. Vitae repudiandae enim et. Sed et et veritatis accusamus vel voluptatem. Nisi sed ea pariatur error incidunt. Inventore earum est non veritatis quibusdam. Non et quia corrupti maxime.",
      stock: 165,
    },
    {
      id: 72,
      category_id: 70,
      reference: "na-tt7cq-K",
      width: 14.1,
      height: 14.22,
      price: 12.25,
      thumbnail: "https://marmelab.com/posters/nature-3.jpeg",
      image: "https://marmelab.com/posters/nature-3.jpeg",
      description:
        "Est ipsum velit facilis voluptatem sed doloribus. Necessitatibus excepturi dicta. Sed eos accusantium quam ut quae similique. Ab sint ullam amet amet non fugiat odio ipsam. Voluptatem aut maiores explicabo maiores aliquam ut voluptas eius. Earum cumque ducimus voluptas delectus ea ea.",
      stock: 26,
    },
    {
      id: 73,
      category_id: 70,
      reference: "na-glbs3-D",
      width: 13.05,
      height: 27.31,
      price: 22.14,
      thumbnail: "https://marmelab.com/posters/nature-4.jpeg",
      image: "https://marmelab.com/posters/nature-4.jpeg",
      description:
        "Unde iste inventore ducimus vero labore. Odio ullam fuga eius sit commodi ex. In minima voluptate doloremque. Ex quo veniam maxime perferendis et soluta accusantium aut aut. Dolorem qui ducimus blanditiis similique qui minus doloremque. Dolore necessitatibus ut ipsam nesciunt.",
      stock: 1,
    },
    {
      id: 74,
      category_id: 70,
      reference: "na-x6wd9-P",
      width: 18.94,
      height: 31.75,
      price: 32.05,
      thumbnail: "https://marmelab.com/posters/nature-5.jpeg",
      image: "https://marmelab.com/posters/nature-5.jpeg",
      description:
        "Libero minus ut eos. Voluptatem rerum aut magni enim voluptatem. Fugiat temporibus aut omnis ipsum perspiciatis delectus similique deserunt expedita. Ad et ea cupiditate sapiente alias saepe cum ea quod. Reiciendis officia cum itaque dolore fuga.",
      stock: 200,
    },
    {
      id: 75,
      category_id: 70,
      reference: "na-b0jqh-K",
      width: 24.15,
      height: 23.71,
      price: 37.95,
      thumbnail: "https://marmelab.com/posters/nature-6.jpeg",
      image: "https://marmelab.com/posters/nature-6.jpeg",
      description:
        "Ut atque quia accusamus nam quas aperiam. Laboriosam quod optio perferendis est. Odio laudantium illum dolore. Totam consectetur nisi illo voluptatibus nulla.",
      stock: 176,
    },
    {
      id: 76,
      category_id: 70,
      reference: "na-uc2h1-L",
      width: 35.24,
      height: 27.22,
      price: 49.98,
      thumbnail: "https://marmelab.com/posters/nature-7.jpeg",
      image: "https://marmelab.com/posters/nature-7.jpeg",
      description:
        "Nihil et et ad aliquid. Rerum numquam modi. Voluptatem molestiae maxime aperiam et veniam nostrum omnis vero. Nemo aut odio odit provident libero. Pariatur dignissimos temporibus.",
      stock: 167,
    },
    {
      id: 77,
      category_id: 70,
      reference: "na-kv0o2-V",
      width: 34.21,
      height: 29.75,
      price: 63.93,
      thumbnail: "https://marmelab.com/posters/nature-8.jpeg",
      image: "https://marmelab.com/posters/nature-8.jpeg",
      description:
        "Culpa optio et placeat numquam blanditiis ut voluptate accusamus sit. Et consequatur non enim voluptatem autem. Provident qui dignissimos ducimus facere cum voluptatem ea. Debitis vel perferendis minus voluptas sint distinctio ab magni. Sed aliquam commodi autem eos.",
      stock: 160,
    },
    {
      id: 78,
      category_id: 70,
      reference: "na-rns8z-W",
      width: 22.84,
      height: 25.5,
      price: 36.91,
      thumbnail: "https://marmelab.com/posters/nature-9.jpeg",
      image: "https://marmelab.com/posters/nature-9.jpeg",
      description:
        "Quos in veniam qui dolore ad repellendus minima. Asperiores esse repudiandae optio. Doloremque sunt perspiciatis omnis maxime a ipsa eos. Atque tempore beatae ut tenetur qui vitae sed.",
      stock: 68,
    },
    {
      id: 79,
      category_id: 70,
      reference: "na-80rl3-U",
      width: 26.41,
      height: 35.95,
      price: 53.81,
      thumbnail: "https://marmelab.com/posters/nature-10.jpeg",
      image: "https://marmelab.com/posters/nature-10.jpeg",
      description:
        "Eos non eos sit rerum quae dolorem. Dolores ducimus dolorem aperiam perferendis qui. Maiores tenetur quisquam dolorem beatae aut doloremque velit. Ut ut est soluta. Neque dolores consequuntur quis est velit. Consequuntur minima corrupti eius nostrum molestiae.",
      stock: 126,
    },
    // people
    {
      id: 80,
      category_id: 81,
      reference: "pe-j0ihi-H",
      width: 30.9,
      height: 12.74,
      price: 20.13,
      thumbnail: "https://marmelab.com/posters/people-1.jpeg",
      image: "https://marmelab.com/posters/people-1.jpeg",
      description:
        "Repudiandae molestiae in occaecati alias rerum qui debitis ratione. In quis dolor exercitationem autem sit ut. Id voluptate officia perspiciatis sed qui numquam. Quidem alias error aspernatur libero cum molestias. Veritatis consequuntur quam vitae et et iste.",
      stock: 95,
    },
    {
      id: 81,
      category_id: 81,
      reference: "pe-yvrun-Y",
      width: 13.89,
      height: 35.98,
      price: 25.61,
      thumbnail: "https://marmelab.com/posters/people-2.jpeg",
      image: "https://marmelab.com/posters/people-2.jpeg",
      description:
        "Autem beatae praesentium sapiente saepe. Perferendis consectetur quia earum inventore enim voluptas quam nesciunt perspiciatis. Esse id quos molestiae et in temporibus. Mollitia reprehenderit quia quibusdam dignissimos velit vel tenetur voluptatum est.",
      stock: 159,
    },
    {
      id: 82,
      category_id: 81,
      reference: "pe-qmww2-T",
      width: 37.21,
      height: 22.2,
      price: 51.13,
      thumbnail: "https://marmelab.com/posters/people-3.jpeg",
      image: "https://marmelab.com/posters/people-3.jpeg",
      description:
        "Velit dolorem voluptates. Error nobis optio rerum qui facere ipsum enim illum aliquid. Placeat et laudantium ut.",
      stock: 0,
    },
    {
      id: 83,
      category_id: 81,
      reference: "pe-p8ite-J",
      width: 39.3,
      height: 17.85,
      price: 37.11,
      thumbnail: "https://marmelab.com/posters/people-4.jpeg",
      image: "https://marmelab.com/posters/people-4.jpeg",
      description:
        "Perferendis ut reiciendis esse reprehenderit et possimus at hic. Ab ipsum voluptas id et quod repellendus qui occaecati eius. Ut est eveniet beatae inventore. Tempora quas ipsam explicabo adipisci distinctio nisi dignissimos voluptas aperiam. Fugit quia enim et facilis fugiat numquam.",
      stock: 3,
    },
    {
      id: 84,
      category_id: 83,
      reference: "pe-ejwqq-D",
      width: 28.13,
      height: 13.61,
      price: 20.57,
      thumbnail: "https://marmelab.com/posters/people-5.jpeg",
      image: "https://marmelab.com/posters/people-5.jpeg",
      description:
        "Voluptas qui asperiores autem perferendis ab maiores placeat repellat magni. Consectetur vel aut repellendus. Autem exercitationem delectus ut. Tenetur sit cupiditate asperiores amet quaerat ut nesciunt facere quibusdam. Eos quo amet eaque nulla molestias quidem alias.",
      stock: 0,
    },
    {
      id: 85,
      category_id: 82,
      reference: "pe-7zeq9-L",
      width: 37.57,
      height: 17.23,
      price: 41.02,
      thumbnail: "https://marmelab.com/posters/people-6.jpeg",
      image: "https://marmelab.com/posters/people-6.jpeg",
      description:
        "Omnis ut id recusandae. Eum consequuntur vel. Et iusto error provident ea sunt nihil. Ut sunt eligendi repudiandae qui tenetur. Explicabo consectetur doloremque ea impedit porro sunt.",
      stock: 153,
    },
    {
      id: 86,
      category_id: 83,
      reference: "pe-z9fmp-C",
      width: 37.07,
      height: 10.07,
      price: 22.55,
      thumbnail: "https://marmelab.com/posters/people-7.jpeg",
      image: "https://marmelab.com/posters/people-7.jpeg",
      description:
        "Non officiis fugiat molestiae optio voluptatum omnis. Esse non aperiam hic similique. Recusandae et quia quas molestiae sed temporibus. Ullam autem vitae. Incidunt unde nisi ut vel.",
      stock: 76,
    },
    {
      id: 87,
      category_id: 81,
      reference: "pe-tskdn-O",
      width: 19.79,
      height: 26.13,
      price: 28,
      thumbnail: "https://marmelab.com/posters/people-8.jpeg",
      image: "https://marmelab.com/posters/people-8.jpeg",
      description:
        "Eos et fugit distinctio ut. Voluptatibus non quas quas vel aliquid numquam. Molestias quidem itaque tempore et qui ab. Qui vel eum officia consequuntur omnis velit odit neque. Aut aut nam beatae rerum porro molestias doloribus quaerat. Ipsum accusamus sit quaerat.",
      stock: 133,
    },
    {
      id: 88,
      category_id: 83,
      reference: "pe-f7mg4-R",
      width: 28.84,
      height: 30.85,
      price: 54.04,
      thumbnail: "https://marmelab.com/posters/people-9.jpeg",
      image: "https://marmelab.com/posters/people-9.jpeg",
      description:
        "Omnis quia laborum ut nihil omnis. Nesciunt sint placeat amet consequatur necessitatibus. Natus fuga dolorum corporis. Voluptatem consequatur at repellat. Eos provident distinctio quam enim totam ut.",
      stock: 186,
    },
    {
      id: 89,
      category_id: 83,
      reference: "pe-muhcr-C",
      width: 25.81,
      height: 30.27,
      price: 47.54,
      thumbnail: "https://marmelab.com/posters/people-10.jpeg",
      image: "https://marmelab.com/posters/people-10.jpeg",
      description:
        "Eos quo eveniet dolorum quod quia non molestias. Sit optio optio est ipsum voluptatum consequatur distinctio praesentium sequi. Enim et et aut ut. Consequuntur sunt temporibus vitae vero et fuga. Omnis ipsum voluptate molestiae nostrum et ut.",
      stock: 35,
    },
    // sports
    {
      id: 90,
      category_id: 90,
      reference: "sp-he8h6-Z",
      width: 25.49,
      height: 22.7,
      price: 33.67,
      thumbnail: "https://marmelab.com/posters/sports-1.jpeg",
      image: "https://marmelab.com/posters/sports-1.jpeg",
      description:
        "Cumque est cupiditate. Et minima ab laborum itaque quo facere. Sed consequatur ut minima dolor. Assumenda maxime debitis asperiores accusantium est pariatur. Blanditiis rerum et.",
      stock: 220,
    },
    {
      id: 91,
      category_id: 90,
      reference: "sp-j4el3-Q",
      width: 31.35,
      height: 35.33,
      price: 64.88,
      thumbnail: "https://marmelab.com/posters/sports-2.jpeg",
      image: "https://marmelab.com/posters/sports-2.jpeg",
      description:
        "Earum aut rerum qui rerum accusantium adipisci eum quod qui. Totam sint qui recusandae dolores sint. Impedit porro aut. Et aspernatur corrupti. Officia sit ipsa voluptatem ab excepturi eos dolor et tempora.",
      stock: 85,
    },
    {
      id: 92,
      category_id: 90,
      reference: "sp-uo3iu-C",
      width: 20.95,
      height: 25.1,
      price: 31.67,
      thumbnail: "https://marmelab.com/posters/sports-3.jpeg",
      image: "https://marmelab.com/posters/sports-3.jpeg",
      description:
        "Dolores et explicabo odio odio porro facilis quam ducimus. Quasi fuga qui modi nemo corrupti. Quia vel tenetur voluptas quam voluptatum quis. Ut ut asperiores sit earum harum voluptatum totam ipsum rerum. Sequi ducimus et eligendi adipisci reprehenderit laudantium non. Ad cupiditate mollitia consequatur ut quam officiis.",
      stock: 0,
    },
    {
      id: 93,
      category_id: 90,
      reference: "sp-bhkks-V",
      width: 39.01,
      height: 13.97,
      price: 33.7,
      thumbnail: "https://marmelab.com/posters/sports-4.jpeg",
      image: "https://marmelab.com/posters/sports-4.jpeg",
      description:
        "Beatae porro eos autem repudiandae. Adipisci similique deleniti non aliquam. Incidunt reiciendis enim dolore saepe inventore. Esse dolorem reiciendis quibusdam corrupti.",
      stock: 75,
    },
    {
      id: 94,
      category_id: 90,
      reference: "sp-lcrom-Q",
      width: 31.44,
      height: 38.12,
      price: 73.82,
      thumbnail: "https://marmelab.com/posters/sports-5.jpeg",
      image: "https://marmelab.com/posters/sports-5.jpeg",
      description:
        "Nisi minima dolorem molestiae dolorem animi minima dolore. Voluptas quisquam error. Quibusdam cupiditate ut repellat labore et quia et eaque deserunt. Quas sed voluptatem id omnis.",
      stock: 42,
    },
    {
      id: 95,
      category_id: 90,
      reference: "sp-yhhs2-A",
      width: 14.62,
      height: 11.46,
      price: 10.37,
      thumbnail: "https://marmelab.com/posters/sports-6.jpeg",
      image: "https://marmelab.com/posters/sports-6.jpeg",
      description:
        "Similique cupiditate nisi deleniti nihil expedita. Dolore veniam veniam sint accusamus cupiditate iste est officiis et. Repudiandae autem quod dolor qui magni ex non. Tempora suscipit autem laudantium qui consectetur.",
      stock: 82,
    },
    {
      id: 96,
      category_id: 90,
      reference: "sp-3h5hy-J",
      width: 18.66,
      height: 33.56,
      price: 38.98,
      thumbnail: "https://marmelab.com/posters/sports-7.jpeg",
      image: "https://marmelab.com/posters/sports-7.jpeg",
      description:
        "Eius qui libero et eum modi. Sed sequi suscipit sit temporibus delectus nulla non exercitationem. Consequuntur magnam voluptatem. Dolores maiores sit earum et dolorem suscipit sint sit.",
      stock: 70,
    },
    {
      id: 97,
      category_id: 90,
      reference: "sp-q5tt6-S",
      width: 23.01,
      height: 33.04,
      price: 44.2,
      thumbnail: "https://marmelab.com/posters/sports-8.jpeg",
      image: "https://marmelab.com/posters/sports-8.jpeg",
      description:
        "Quas dolores blanditiis dicta velit unde. Eaque quisquam maxime. Debitis occaecati asperiores possimus assumenda.",
      stock: 250,
    },
    {
      id: 98,
      category_id: 90,
      reference: "sp-jzc7u-N",
      width: 37.87,
      height: 16.36,
      price: 37.83,
      thumbnail: "https://marmelab.com/posters/sports-9.jpeg",
      image: "https://marmelab.com/posters/sports-9.jpeg",
      description:
        "Autem odit aut. Non voluptatibus ut. Est id velit qui aliquam dicta.",
      stock: 0,
    },
    {
      id: 99,
      category_id: 90,
      reference: "sp-a6pn9-V",
      width: 32.72,
      height: 24.26,
      price: 39.89,
      thumbnail: "https://marmelab.com/posters/sports-10.jpeg",
      image: "https://marmelab.com/posters/sports-10.jpeg",
      description:
        "Consectetur eius suscipit in. Sunt et beatae. Totam odio dolore quibusdam ducimus ut nemo necessitatibus autem. Doloremque ipsum beatae et libero deserunt omnis omnis vitae fuga.",
      stock: 0,
    },
    // tech
    {
      id: 100,
      category_id: 100,
      reference: "te-jisve-T",
      width: 12.19,
      height: 25.77,
      price: 15.91,
      thumbnail: "https://marmelab.com/posters/tech-1.jpeg",
      image: "https://marmelab.com/posters/tech-1.jpeg",
      description:
        "Odio ullam eligendi et suscipit molestiae ipsa. Tenetur aperiam ut tempora sed aut aut. Enim ut quod corporis similique sint corrupti eveniet itaque qui. Inventore rerum qui expedita tenetur iure sapiente pariatur molestiae.",
      stock: 192,
    },
    {
      id: 101,
      category_id: 100,
      reference: "te-v3d8n-W",
      width: 21.01,
      height: 18.14,
      price: 21.11,
      thumbnail: "https://marmelab.com/posters/tech-2.jpeg",
      image: "https://marmelab.com/posters/tech-2.jpeg",
      description:
        "Voluptas delectus impedit ab quia. Pariatur eveniet qui rerum aliquam. Aspernatur voluptates velit tempore et molestias. Exercitationem repellat quaerat voluptatum ipsam illum qui suscipit atque minima. Dolorum aliquam impedit voluptatem qui et eveniet adipisci vel eaque. Ex aut et earum.",
      stock: 226,
    },
    {
      id: 102,
      category_id: 100,
      reference: "te-gt9tt-G",
      width: 35.75,
      height: 17.4,
      price: 38.7,
      thumbnail: "https://marmelab.com/posters/tech-3.jpeg",
      image: "https://marmelab.com/posters/tech-3.jpeg",
      description:
        "Asperiores enim et tempore rerum dolore optio. Adipisci sequi illo est eveniet molestiae distinctio. Explicabo laudantium odit nihil saepe eveniet itaque est. Tempora natus maiores hic et excepturi et ex provident nam. Sunt facilis repellendus beatae qui et explicabo molestiae.",
      stock: 6,
    },
    {
      id: 103,
      category_id: 100,
      reference: "te-thmmq-L",
      width: 15.24,
      height: 30.67,
      price: 30.29,
      thumbnail: "https://marmelab.com/posters/tech-4.jpeg",
      image: "https://marmelab.com/posters/tech-4.jpeg",
      description:
        "Eligendi fuga adipisci velit sint error qui consequuntur debitis error. Est minus et tempora maxime nihil aliquid. Enim laboriosam repudiandae. Doloremque harum quo omnis consequatur est sint id. Unde officia saepe dolor expedita magnam quo eveniet possimus. Non quisquam voluptates dolore reprehenderit facilis dolorem dignissimos rerum vel.",
      stock: 0,
    },
    {
      id: 104,
      category_id: 100,
      reference: "te-k147m-E",
      width: 23,
      height: 30.67,
      price: 45.29,
      thumbnail: "https://marmelab.com/posters/tech-5.jpeg",
      image: "https://marmelab.com/posters/tech-5.jpeg",
      description:
        "Iste quia officia id qui aspernatur recusandae est sequi ratione. Debitis et tenetur voluptatum quisquam quo qui. Sunt rerum assumenda. Libero at sed tenetur. Corporis tempora qui ad laboriosam qui aut sit. Rerum voluptate reprehenderit.",
      stock: 72,
    },
    {
      id: 105,
      category_id: 100,
      reference: "te-cshyu-I",
      width: 39.72,
      height: 32.13,
      price: 66.24,
      thumbnail: "https://marmelab.com/posters/tech-6.jpeg",
      image: "https://marmelab.com/posters/tech-6.jpeg",
      description:
        "Qui illum magnam natus sed consectetur accusantium amet. Maxime ad ullam architecto magni aut quibusdam esse. Qui reiciendis cupiditate corporis velit fugiat aperiam quidem quam. Nemo rerum aut eum. Sequi aut vitae dignissimos. Qui aut laborum tempore libero.",
      stock: 189,
    },
    {
      id: 106,
      category_id: 100,
      reference: "te-mrhu7-V",
      width: 29.16,
      height: 14.93,
      price: 29,
      thumbnail: "https://marmelab.com/posters/tech-7.jpeg",
      image: "https://marmelab.com/posters/tech-7.jpeg",
      description:
        "Sit aut perspiciatis nobis. Aspernatur sunt quae molestias consequatur velit qui voluptas impedit ut. Animi neque earum soluta beatae tempora illum molestias impedit accusamus.",
      stock: 127,
    },
    {
      id: 107,
      category_id: 100,
      reference: "te-eyepy-H",
      width: 26.39,
      height: 17.76,
      price: 26.77,
      thumbnail: "https://marmelab.com/posters/tech-8.jpeg",
      image: "https://marmelab.com/posters/tech-8.jpeg",
      description:
        "Iure provident temporibus praesentium consequatur occaecati et enim accusantium cumque. Cumque doloribus et ut ex autem et commodi omnis. Porro hic vel a dolores. Facilis itaque enim quis odio. At ratione nobis eos molestias iste impedit praesentium laudantium quidem.",
      stock: 118,
    },
    {
      id: 108,
      category_id: 100,
      reference: "te-y52ry-N",
      width: 38.5,
      height: 31.6,
      price: 66.11,
      thumbnail: "https://marmelab.com/posters/tech-9.jpeg",
      image: "https://marmelab.com/posters/tech-9.jpeg",
      description:
        "Est impedit modi repudiandae sed soluta architecto enim in reiciendis. Et esse quas praesentium. Quis et ipsa illum autem facere aspernatur.",
      stock: 0,
    },
    {
      id: 109,
      category_id: 100,
      reference: "te-dyli7-Y",
      width: 13.21,
      height: 13.78,
      price: 9.31,
      thumbnail: "https://marmelab.com/posters/tech-10.jpeg",
      image: "https://marmelab.com/posters/tech-10.jpeg",
      description:
        "Quo consectetur rem esse quia. Autem omnis voluptatem porro veritatis dolores ullam blanditiis sint omnis. Illo quia rerum voluptatem eveniet vel magni corporis asperiores in.",
      stock: 161,
    },
    //travel
    {
      id: 110,
      category_id: 110,
      reference: "tr-e5lu5-M",
      width: 10.57,
      height: 31.27,
      price: 20.91,
      thumbnail: "https://marmelab.com/posters/travel-1.jpeg",
      image: "https://marmelab.com/posters/travel-1.jpeg",
      description:
        "Ut et voluptas quia autem animi illum tempore ea. Quia vitae voluptatibus ullam maiores neque cum. Consectetur nostrum velit necessitatibus voluptas ullam. Corrupti ipsam quia reprehenderit ad.",
      stock: 224,
    },
    {
      id: 111,
      category_id: 110,
      reference: "tr-qzzxx-J",
      width: 16.1,
      height: 30.79,
      price: 28.39,
      thumbnail: "https://marmelab.com/posters/travel-2.jpeg",
      image: "https://marmelab.com/posters/travel-2.jpeg",
      description:
        "Et quis dolores illum recusandae in doloribus quo. Est ea velit omnis ex non voluptates. Repudiandae unde tenetur et eaque unde. Quia temporibus sit accusamus doloremque voluptas error a fugiat. Aliquid est aliquam quia ducimus itaque.",
      stock: 15,
    },
    {
      id: 112,
      category_id: 110,
      reference: "tr-u4orn-L",
      width: 37.26,
      height: 39.79,
      price: 84.43,
      thumbnail: "https://marmelab.com/posters/travel-3.jpeg",
      image: "https://marmelab.com/posters/travel-3.jpeg",
      description:
        "Ab ut quidem cumque corporis accusamus. Sed consectetur et nisi. Eos nihil cupiditate. Nesciunt voluptatem aut. Voluptas aut aut dolores. Nobis aut placeat.",
      stock: 150,
    },
    {
      id: 113,
      category_id: 110,
      reference: "tr-x0y4e-X",
      width: 17.21,
      height: 19.35,
      price: 19.54,
      thumbnail: "https://marmelab.com/posters/travel-4.jpeg",
      image: "https://marmelab.com/posters/travel-4.jpeg",
      description:
        "Nisi in ut. Magni delectus quidem aliquid et aut. Ea odit omnis qui enim. Dolore et et ipsa dolor molestias quis.",
      stock: 164,
    },
    {
      id: 114,
      category_id: 110,
      reference: "tr-n1581-Z",
      width: 37.01,
      height: 20.23,
      price: 41.8,
      thumbnail: "https://marmelab.com/posters/travel-5.jpeg",
      image: "https://marmelab.com/posters/travel-5.jpeg",
      description:
        "Nostrum voluptatem autem dolorem hic officiis. Mollitia qui quia quae odit totam placeat. Quibusdam est molestiae laudantium iure ut quos qui. Iste et assumenda quibusdam. Molestiae hic nostrum beatae dolor minima numquam perspiciatis qui voluptas. Repellendus quia maiores.",
      stock: 66,
    },
    {
      id: 115,
      category_id: 110,
      reference: "tr-bm59a-N",
      width: 13.4,
      height: 15.62,
      price: 10.82,
      thumbnail: "https://marmelab.com/posters/travel-6.jpeg",
      image: "https://marmelab.com/posters/travel-6.jpeg",
      description:
        "Et blanditiis quas voluptatem sint magnam labore. Molestiae qui voluptas id molestiae nam est aspernatur. Non eos voluptates qui esse assumenda.",
      stock: 27,
    },
    {
      id: 116,
      category_id: 110,
      reference: "tr-us7x6-C",
      width: 10.45,
      height: 32.74,
      price: 19.23,
      thumbnail: "https://marmelab.com/posters/travel-7.jpeg",
      image: "https://marmelab.com/posters/travel-7.jpeg",
      description:
        "Dolorum numquam sed incidunt saepe adipisci quod. Ut dolorem fugiat aut quia pariatur tenetur tempora in autem. Accusamus qui temporibus voluptas minus labore est nam sit enim.",
      stock: 86,
    },
    {
      id: 117,
      category_id: 110,
      reference: "tr-dhfn9-N",
      width: 30.87,
      height: 25.61,
      price: 51.91,
      thumbnail: "https://marmelab.com/posters/travel-8.jpeg",
      image: "https://marmelab.com/posters/travel-8.jpeg",
      description:
        "Repellat corrupti et dolor est. Perspiciatis modi quisquam ex dolores totam consectetur magni. Minus asperiores ipsum sapiente facere perspiciatis voluptatem vel quia. Occaecati harum eius impedit sit pariatur commodi assumenda.",
      stock: 43,
    },
    {
      id: 118,
      category_id: 110,
      reference: "tr-qser9-R",
      width: 31.14,
      height: 15.54,
      price: 28.54,
      thumbnail: "https://marmelab.com/posters/travel-9.jpeg",
      image: "https://marmelab.com/posters/travel-9.jpeg",
      description:
        "Aut nam provident vel aliquid aut odit nesciunt consequatur sunt. Recusandae accusamus odit explicabo sunt soluta atque voluptate itaque. Distinctio ducimus velit sunt ipsam. Aut dolor dolorem.",
      stock: 63,
    },
    {
      id: 119,
      category_id: 110,
      reference: "tr-zypv4-B",
      width: 27.79,
      height: 25.89,
      price: 36.19,
      thumbnail: "https://marmelab.com/posters/travel-10.jpeg",
      image: "https://marmelab.com/posters/travel-10.jpeg",
      description:
        "Reprehenderit consequatur et est soluta consequatur id et harum accusantium. Omnis in asperiores culpa eligendi. Vero molestiae impedit eum modi neque ipsa sint. Corrupti nisi autem. Velit porro dolores a. Odit error minus eligendi voluptatibus nostrum.",
      stock: 48,
    },
    // water
    {
      id: 120,
      category_id: 120,
      reference: "wa-fs8yo-T",
      width: 10.38,
      height: 38.21,
      price: 23.37,
      thumbnail: "https://marmelab.com/posters/water-1.jpeg",
      image: "https://marmelab.com/posters/water-1.jpeg",
      description:
        "Quia fugiat consequatur voluptas dolorem et. Et perferendis reiciendis enim et sit dolor qui excepturi sunt. Aperiam voluptatem odit et aspernatur. Ea tempore ea et esse voluptatem. Omnis vitae eaque quia fuga culpa possimus.",
      stock: 31,
    },
    {
      id: 121,
      category_id: 120,
      reference: "wa-ahvz3-P",
      width: 17.14,
      height: 13.16,
      price: 14.07,
      thumbnail: "https://marmelab.com/posters/water-2.jpeg",
      image: "https://marmelab.com/posters/water-2.jpeg",
      description:
        "Voluptatem nostrum dolorum qui autem vitae ducimus possimus qui ipsam. Pariatur est omnis aspernatur ut quia amet. Fuga vitae non doloremque omnis adipisci eaque. Blanditiis laboriosam ad est aut ipsa velit adipisci. Commodi hic ut incidunt velit eligendi possimus repudiandae.",
      stock: 239,
    },
    {
      id: 122,
      category_id: 120,
      reference: "wa-aljc6-L",
      width: 17.98,
      height: 33.25,
      price: 34.01,
      thumbnail: "https://marmelab.com/posters/water-3.jpeg",
      image: "https://marmelab.com/posters/water-3.jpeg",
      description:
        "Ad et amet voluptatibus incidunt earum aperiam enim voluptatibus. Ad omnis quo minima voluptas temporibus accusamus blanditiis rerum aut. Eveniet molestiae accusamus qui eligendi ut omnis eligendi laborum tempora.",
      stock: 97,
    },
    {
      id: 123,
      category_id: 120,
      reference: "wa-fhxdq-C",
      width: 26.23,
      height: 19.87,
      price: 30.06,
      thumbnail: "https://marmelab.com/posters/water-4.jpeg",
      image: "https://marmelab.com/posters/water-4.jpeg",
      description:
        "Deserunt nesciunt itaque natus sunt voluptatem. Unde voluptatum assumenda sequi ut non. Fugiat et et hic ut sint ut quia. Assumenda praesentium aut quam ea. Nemo ratione ducimus nostrum fugit.",
      stock: 149,
    },
    {
      id: 124,
      category_id: 120,
      reference: "wa-psp3p-Q",
      width: 33.94,
      height: 19.35,
      price: 36.02,
      thumbnail: "https://marmelab.com/posters/water-5.jpeg",
      image: "https://marmelab.com/posters/water-5.jpeg",
      description:
        "Natus porro qui dolore aut vitae quidem dignissimos qui illum. Molestiae repellendus est sed. Et harum ut natus et nihil reiciendis fugiat pariatur aut. Eum commodi autem.",
      stock: 0,
    },
    {
      id: 125,
      category_id: 120,
      reference: "wa-gltyw-R",
      width: 38.95,
      height: 18.46,
      price: 36.08,
      thumbnail: "https://marmelab.com/posters/water-6.jpeg",
      image: "https://marmelab.com/posters/water-6.jpeg",
      description:
        "Quo odio voluptates libero nulla. Doloremque quaerat nemo molestias. Delectus officia rem quam libero.",
      stock: 0,
    },
    {
      id: 126,
      category_id: 120,
      reference: "wa-d3ijh-R",
      width: 36.6,
      height: 13.18,
      price: 28.81,
      thumbnail: "https://marmelab.com/posters/water-7.jpeg",
      image: "https://marmelab.com/posters/water-7.jpeg",
      description:
        "Iure unde et fugiat amet. Quia eum consequatur eligendi. Voluptatem qui excepturi numquam vero qui deserunt vitae quae minima. Autem harum ipsa non. Eaque dicta rerum et consequatur cumque deserunt non soluta id.",
      stock: 245,
    },
    {
      id: 127,
      category_id: 120,
      reference: "wa-dabwr-B",
      width: 24.16,
      height: 39.47,
      price: 50.12,
      thumbnail: "https://marmelab.com/posters/water-8.jpeg",
      image: "https://marmelab.com/posters/water-8.jpeg",
      description:
        "Ea atque veniam quis. Veniam voluptas corporis harum consequatur. Hic maiores quia aut illo expedita optio recusandae.",
      stock: 172,
    },
    {
      id: 128,
      category_id: 120,
      reference: "wa-m935j-G",
      width: 33.57,
      height: 14.03,
      price: 31.36,
      thumbnail: "https://marmelab.com/posters/water-9.jpeg",
      image: "https://marmelab.com/posters/water-9.jpeg",
      description:
        "Omnis modi culpa recusandae nobis nemo omnis quia eveniet. Et aspernatur natus. Modi quia repellendus ut voluptates fugiat repellat quod.",
      stock: 0,
    },
    {
      id: 129,
      category_id: 120,
      reference: "wa-91jni-T",
      width: 13.86,
      height: 19.7,
      price: 14.13,
      thumbnail: "https://marmelab.com/posters/water-10.jpeg",
      image: "https://marmelab.com/posters/water-10.jpeg",
      description:
        "Modi assumenda asperiores laborum quis. Ipsa eius quas eum et. Reiciendis culpa voluptate ut ducimus cupiditate dolores similique quia sed. Sed voluptatem et cum doloremque consequuntur velit explicabo cumque nihil. Aperiam facilis enim expedita dolores vero iste.",
      stock: 130,
    },
  ],
};
