name: "Test - action"

on:
  push:
    branches:
      - master

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Install
      run: make install
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build Website
      run: make build
      env:
        CI: true
        GENERATE_SOURCEMAP: false
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build 
